version: '3.7'

services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
      POSTGRES_DB: PostgresDB
    ports:
      - "5432:5432"
    networks:
      - shoppinglistnetwork
  
  spring-app:
    build:
      context: ./shoppinglist
      dockerfile: Dockerfile
    container_name: BackendContainer
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PostgresDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      OTEL_SERVICE_NAME: spring-app
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_METRICS_EXPORTER: none
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
    networks:
      - shoppinglistnetwork


  shoppinglistui:
    build:
      context: ./shoppinglistui
      dockerfile: Dockerfile
    container_name: FrontendContainer
    ports:
      - "3000:3000"
    depends_on:
      - spring-app
    networks:
      - shoppinglistnetwork
  
  jaeger-service:
      container_name: jaeger
      image: jaegertracing/all-in-one:latest
      ports:
        - "16686:16686"
        - "14250:14250"
      networks:
        - shoppinglistnetwork


networks:
  shoppinglistnetwork:
    driver: bridge
